# Generated by Django 6.1 on 2026-08-19 06:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отделения')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Код')),
                ('head', models.CharField(blank=True, max_length=150, verbose_name='Заведующий отделением')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('document_name', models.CharField(blank=True, max_length=200, verbose_name='Название документа')),
            ],
            options={
                'verbose_name': 'Тип приказа',
                'verbose_name_plural': 'Типы приказов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название группы')),
                ('course', models.PositiveSmallIntegerField(default=1, verbose_name='Курс')),
                ('enroll_year', models.PositiveSmallIntegerField(verbose_name='Год набора')),
                ('curator', models.CharField(blank=True, max_length=150, verbose_name='Куратор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='contingent.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер приказа')),
                ('date', models.DateField(verbose_name='Дата приказа')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён')], default='draft', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contingent.ordertype', verbose_name='Тип приказа')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RegistryExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования')),
                ('period_start', models.DateField(verbose_name='Период с')),
                ('period_end', models.DateField(verbose_name='Период по')),
                ('student_status', models.CharField(blank=True, max_length=30, verbose_name='Статус студентов')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='Студентов в выгрузке')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Приказов в выгрузке')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('xml_file', models.FileField(upload_to='registry_exports/%Y/%m/', verbose_name='XML-файл')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Контрольная сумма SHA-256')),
                ('status', models.CharField(choices=[('draft', 'Сформирован'), ('ready', 'Готов к отправке'), ('sent', 'Отправлен'), ('error', 'Ошибка валидации')], default='draft', max_length=20, verbose_name='Статус')),
                ('validation_errors', models.TextField(blank=True, verbose_name='Ошибки валидации')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='contingent.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Выгрузка в Реестр СПО',
                'verbose_name_plural': 'Выгрузки в Реестр СПО',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код специальности')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('qualification', models.CharField(blank=True, max_length=150, verbose_name='Квалификация')),
                ('duration_months', models.PositiveSmallIntegerField(default=46, verbose_name='Срок обучения, мес.')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='contingent.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='contingent.specialty', verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('snils', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='СНИЛС должен иметь формат 000-000-000 00', regex='^\\d{3}-\\d{3}-\\d{3} \\d{2}$')], verbose_name='СНИЛС')),
                ('citizenship', models.CharField(default='Россия', max_length=100, verbose_name='Гражданство')),
                ('status', models.CharField(choices=[('study', 'Обучается'), ('academic_leave', 'Академический отпуск'), ('expelled', 'Отчислен'), ('graduated', 'Окончил обучение')], db_index=True, default='study', max_length=20, verbose_name='Статус')),
                ('student_card_number', models.CharField(max_length=20, unique=True, verbose_name='Номер личного дела')),
                ('enroll_date', models.DateField(blank=True, null=True, verbose_name='Дата зачисления')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address_index', models.CharField(blank=True, max_length=6, verbose_name='Индекс')),
                ('address_city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('address_street', models.CharField(blank=True, max_length=150, verbose_name='Улица')),
                ('address_house', models.CharField(blank=True, max_length=20, verbose_name='Дом')),
                ('address_flat', models.CharField(blank=True, max_length=10, verbose_name='Квартира')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='contingent.group', verbose_name='Группа')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='contingent.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='contingent.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enroll', 'Зачислить'), ('expel', 'Отчислить'), ('transfer', 'Перевести'), ('academic_leave', 'Академ. отпуск'), ('recover', 'Восстановить')], max_length=30, verbose_name='Действие')),
                ('basis', models.CharField(blank=True, max_length=300, verbose_name='Основание')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('group_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contingent.group', verbose_name='Из группы')),
                ('group_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contingent.group', verbose_name='В группу')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contingent.order', verbose_name='Приказ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='contingent.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Пункт приказа',
                'verbose_name_plural': 'Пункты приказа',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Начало')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='Причина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_leaves', to='contingent.order', verbose_name='Приказ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_leaves', to='contingent.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Академический отпуск',
                'verbose_name_plural': 'Академические отпуска',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Паспорт'), ('birth_certificate', 'Свидетельство о рождении'), ('snils_cert', 'СНИЛС'), ('diploma', 'Аттестат / диплом'), ('other', 'Прочее')], default='passport', max_length=30, verbose_name='Тип документа')),
                ('series', models.CharField(blank=True, max_length=20, verbose_name='Серия')),
                ('number', models.CharField(max_length=30, verbose_name='Номер')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(blank=True, max_length=300, verbose_name='Кем выдан')),
                ('issue_code', models.CharField(blank=True, max_length=20, verbose_name='Код подразделения')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной документ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contingent.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Документ студента',
                'verbose_name_plural': 'Документы студентов',
                'ordering': ['-is_main', 'doc_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(blank=True, choices=[('study', 'Обучается'), ('academic_leave', 'Академический отпуск'), ('expelled', 'Отчислен'), ('graduated', 'Окончил обучение')], max_length=20, verbose_name='Было')),
                ('status_to', models.CharField(choices=[('study', 'Обучается'), ('academic_leave', 'Академический отпуск'), ('expelled', 'Отчислен'), ('graduated', 'Окончил обучение')], max_length=20, verbose_name='Стало')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата изменения')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='contingent.order', verbose_name='Приказ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='contingent.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Запись движения контингента',
                'verbose_name_plural': 'Движение контингента',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('number', 'date'), name='uniq_order_number_date'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['group'], name='contingent__group_i_91fdd7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='contingent__status_6cb28c_idx'),
        ),
    ]
