# Generated by Django 6.1 on 2026-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0003_ordertype_file_code_ordertype_file_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinfo',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Паспорт: номер'),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, verbose_name='Паспорт: серия'),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='relation',
            field=models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('guardian', 'Опекун / попечитель'), ('representative', 'Законный представитель')], default='mother', max_length=20, verbose_name='Степень родства'),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='workplace',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место работы'),
        ),
    ]
