# Generated by Django 6.1 on 2026-08-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование должности')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Отделение / подразделение')),
                ('rate_count', models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='Количество ставок')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оклад (руб.)')),
            ],
            options={
                'verbose_name': 'Должность (штатное расписание)',
                'verbose_name_plural': 'Штатное расписание',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TarificationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('year_start', models.PositiveSmallIntegerField(verbose_name='Учебный год (начало)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждена')], default='draft', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Период тарификации',
                'verbose_name_plural': 'Тарификация',
                'ordering': ['-year_start'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('gender', models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='Место рождения')),
                ('citizenship', models.CharField(default='Россия', max_length=100, verbose_name='Гражданство')),
                ('snils', models.CharField(blank=True, max_length=14, verbose_name='СНИЛС')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('passport_series', models.CharField(blank=True, max_length=10, verbose_name='Паспорт: серия')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Паспорт: номер')),
                ('passport_issued', models.CharField(blank=True, max_length=300, verbose_name='Паспорт: кем выдан')),
                ('passport_date', models.DateField(blank=True, null=True, verbose_name='Паспорт: дата выдачи')),
                ('category', models.CharField(choices=[('teacher', 'Педагогический работник'), ('management', 'АУП (руководство)'), ('support', 'Вспомогательный персонал')], default='support', max_length=15, verbose_name='Категория')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Отделение / подразделение')),
                ('status', models.CharField(choices=[('active', 'Работает'), ('dismissed', 'Уволен')], default='active', max_length=10, verbose_name='Статус')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма на работу')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('dismissal_reason', models.CharField(blank=True, max_length=300, verbose_name='Основание увольнения')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Образование')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('family_status', models.CharField(blank=True, max_length=100, verbose_name='Семейное положение')),
                ('children_count', models.PositiveSmallIntegerField(default=0, verbose_name='Детей')),
                ('military', models.CharField(blank=True, max_length=100, verbose_name='Воинский учёт')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='schedule.teacher', verbose_name='Профиль преподавателя (расписание)')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='HROrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер приказа')),
                ('date', models.DateField(verbose_name='Дата приказа')),
                ('order_type', models.CharField(choices=[('hire', 'Приём на работу'), ('transfer', 'Перевод'), ('dismiss', 'Увольнение')], default='hire', max_length=10, verbose_name='Тип')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность (по приказу)')),
                ('basis', models.CharField(blank=True, max_length=300, verbose_name='Основание')),
                ('text', models.TextField(blank=True, verbose_name='Текст приказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_orders', to='hr.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Приказ по личному составу',
                'verbose_name_plural': 'Приказы по личному составу',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Ставка')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Назначен с')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffing_units', to='hr.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='hr.staffposition', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Единица штатного расписания',
                'verbose_name_plural': 'Единицы штатного расписания',
                'ordering': ['position__title'],
            },
        ),
        migrations.CreateModel(
            name='TarificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Часов в неделю')),
                ('total_hours', models.PositiveIntegerField(default=0, verbose_name='Часов в год')),
                ('groups', models.CharField(blank=True, max_length=200, verbose_name='Группы')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarification', to='hr.employee', verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarification', to='journal.subject', verbose_name='Дисциплина')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.tarificationperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Строка тарификации',
                'verbose_name_plural': 'Строки тарификации',
                'ordering': ['employee__last_name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('json_file', models.FileField(upload_to='salary_exports/%Y/%m/', verbose_name='JSON-файл')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Контрольная сумма SHA-256')),
                ('status', models.CharField(choices=[('ready', 'Готов к передаче'), ('sent', 'Передан в 1С'), ('error', 'Ошибка')], default='ready', max_length=10, verbose_name='Статус')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='Сотрудников')),
                ('total_hours', models.PositiveIntegerField(default=0, verbose_name='Часов всего')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('tarification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_exports', to='hr.tarificationperiod', verbose_name='Период тарификации')),
            ],
            options={
                'verbose_name': 'Выгрузка в 1С:Зарплата',
                'verbose_name_plural': 'Выгрузки в 1С:Зарплата',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='hr_employee_status_75bd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['category'], name='hr_employee_categor_839a81_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrorder',
            constraint=models.UniqueConstraint(fields=('number', 'date'), name='uniq_hr_order_number_date'),
        ),
        migrations.AddConstraint(
            model_name='tarificationitem',
            constraint=models.UniqueConstraint(fields=('period', 'employee', 'subject'), name='uniq_tarification_period_employee_subject'),
        ),
    ]
