# Generated by Django 6.1 on 2026-09-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='citizenship',
            field=models.CharField(blank=True, default='Россия', max_length=100, verbose_name='Гражданство'),
        ),
    ]
