# Generated by Django 6.1 on 2026-08-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.CharField(choices=[('registry_api', 'REST API Реестра студентов СПО'), ('smev', 'СМЭВ (государственные реестры)')], max_length=20, verbose_name='Интеграция')),
                ('direction', models.CharField(choices=[('out', 'Отправка'), ('in', 'Получение')], max_length=10, verbose_name='Направление')),
                ('endpoint', models.CharField(blank=True, max_length=500, verbose_name='Конечная точка')),
                ('payload', models.TextField(blank=True, verbose_name='Запрос / данные')),
                ('response', models.TextField(blank=True, verbose_name='Ответ')),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('mock', 'Заглушка (без реального подключения)'), ('no_connection', 'Нет подключения'), ('error', 'Ошибка')], default='ok', max_length=15, verbose_name='Статус')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Запись интеграции',
                'verbose_name_plural': 'Журнал интеграций',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmevRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry', models.CharField(choices=[('fns', 'ФНС (ИНН)'), ('pfr', 'СФР (СНИЛС)'), ('zags', 'ЗАГС (акты гражданского состояния)'), ('mvd', 'МВД (паспорт)')], max_length=10, verbose_name='Реестр')),
                ('identifier', models.CharField(max_length=50, verbose_name='Идентификатор (СНИЛС/ИНН/паспорт)')),
                ('person_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('status', models.CharField(choices=[('connected', 'Сведения получены'), ('no_connection', 'Подключение не настроено'), ('error', 'Ошибка')], default='no_connection', max_length=15, verbose_name='Статус')),
                ('response_text', models.TextField(blank=True, verbose_name='Сведения из реестра')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Запрос СМЭВ',
                'verbose_name_plural': 'Запросы СМЭВ',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='StatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('spo1', 'СПО-1 (сведения о сети и численности)'), ('spo2', 'СПО-2 (сведения о материально-технической базе)'), ('monitoring', 'Мониторинг Минпросвещения')], max_length=15, verbose_name='Тип отчёта')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Отчётный год')),
                ('period_date', models.DateField(blank=True, null=True, verbose_name='Дата среза')),
                ('status', models.CharField(choices=[('ready', 'Сформирован'), ('sent', 'Отправлен'), ('error', 'Ошибка')], default='ready', max_length=10, verbose_name='Статус')),
                ('data_json', models.TextField(verbose_name='Данные отчёта (JSON)')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Контрольная сумма SHA-256')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сформирован')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Статистический отчёт',
                'verbose_name_plural': 'Статистические отчёты',
                'ordering': ['-created_at'],
            },
        ),
    ]
