# Generated by Django 6.1 on 2026-08-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contingent', '0002_alter_orderitem_action'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Номер аудитории')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='Корпус')),
                ('capacity', models.PositiveSmallIntegerField(default=30, verbose_name='Вместимость')),
                ('room_type', models.CharField(choices=[('lecture', 'Кабинет'), ('lab', 'Лаборатория'), ('computer', 'Компьютерный класс')], default='lecture', max_length=20, verbose_name='Тип')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='Отделение/кафедра')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели')),
                ('lesson_number', models.PositiveSmallIntegerField(verbose_name='Номер пары')),
                ('week_type', models.CharField(choices=[('every', 'Каждую неделю'), ('odd', 'Нечётная неделя'), ('even', 'Чётная неделя')], default='every', max_length=5, verbose_name='Неделя')),
                ('semester', models.PositiveSmallIntegerField(default=1, verbose_name='Семестр')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='contingent.group', verbose_name='Группа')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='schedule.room', verbose_name='Аудитория')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='journal.subject', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие в расписании',
                'verbose_name_plural': 'Занятия в расписании',
                'ordering': ['day_of_week', 'lesson_number', 'group__name'],
                'indexes': [models.Index(fields=['group', 'semester'], name='schedule_sc_group_i_d46240_idx'), models.Index(fields=['teacher', 'semester'], name='schedule_sc_teacher_0577c0_idx'), models.Index(fields=['room', 'semester'], name='schedule_sc_room_id_fbc22e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.PositiveSmallIntegerField(default=2, verbose_name='Часов в неделю')),
                ('semester', models.PositiveSmallIntegerField(default=1, verbose_name='Семестр')),
                ('exam_type', models.CharField(choices=[('exam', 'Экзамен'), ('credit', 'Зачёт')], default='credit', max_length=10, verbose_name='Вид отчётности')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum', to='contingent.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum', to='journal.subject', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum', to='schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Пункт учебного плана',
                'verbose_name_plural': 'Учебный план',
                'ordering': ['group__name', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'subject', 'semester'), name='uniq_curriculum_group_subject_semester')],
            },
        ),
        migrations.CreateModel(
            name='TeacherUnavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели')),
                ('lesson_number', models.PositiveSmallIntegerField(verbose_name='Номер пары')),
                ('semester', models.PositiveSmallIntegerField(default=1, verbose_name='Семестр')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Причина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable', to='schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Недоступность преподавателя',
                'verbose_name_plural': 'Недоступность преподавателей',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'day_of_week', 'lesson_number', 'semester'), name='uniq_teacher_unavailable')],
            },
        ),
    ]
