# Generated by Django 6.1 on 2026-08-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contingent', '0002_alter_orderitem_action'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('exam', 'Экзамен'), ('credit', 'Зачёт')], default='exam', max_length=10, verbose_name='Вид аттестации')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('room', models.CharField(blank=True, max_length=30, verbose_name='Аудитория')),
                ('teacher', models.CharField(blank=True, max_length=150, verbose_name='Преподаватель')),
                ('form', models.CharField(blank=True, default='Билеты', max_length=100, verbose_name='Форма проведения')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='contingent.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='journal.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Экзамен / зачёт',
                'verbose_name_plural': 'Экзамены и зачёты',
                'ordering': ['date', 'time', 'group__name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('cleared', 'Ликвидирована')], default='active', max_length=10, verbose_name='Статус')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок ликвидации')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата возникновения')),
                ('cleared_at', models.DateField(blank=True, null=True, verbose_name='Дата ликвидации')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_debts', to='contingent.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_debts', to='journal.subject', verbose_name='Дисциплина')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='attestation.exam', verbose_name='Экзамен')),
            ],
            options={
                'verbose_name': 'Академическая задолженность',
                'verbose_name_plural': 'Академические задолженности',
                'ordering': ['-created_at', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('5', '5 (отлично)'), ('4', '4 (хорошо)'), ('3', '3 (удовлетворительно)'), ('2', '2 (неудовлетворительно)'), ('pass', 'Зачтено'), ('fail', 'Не зачтено')], max_length=4, verbose_name='Результат')),
                ('present', models.BooleanField(default=True, verbose_name='Явился')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='attestation.exam', verbose_name='Экзамен')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='contingent.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Результат аттестации',
                'verbose_name_plural': 'Результаты аттестации',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('period_start', models.DateField(verbose_name='Период с')),
                ('period_end', models.DateField(verbose_name='Период по')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён')], default='draft', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('students', models.ManyToManyField(blank=True, related_name='scholarship_periods', to='contingent.student', verbose_name='Студенты (имеют право на стипендию)')),
            ],
            options={
                'verbose_name': 'Стипендиальный период',
                'verbose_name_plural': 'Стипендиальные периоды',
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['group', 'date'], name='attestation_group_i_43a46d_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date'], name='attestation_date_b03a93_idx'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='uniq_result_exam_student'),
        ),
    ]
